### ISSUE TITLE
Codehub commits to Different branch file

### ISSUE THREAD

**Issue by dannyti** [thedillonb/CodeHub#107]
We select a branch and a file , edit the file and you save. It gets saved the first time but the commit gets reflected on the default branch instead of the selected branch. 

Now, when you try to edit second time the same file from the intended branch, we have an error of code sign not matching.

**Comment by thedillonb** [comment]
This has been fixed in the latest version (2.3.4). Sorry for the long delay on this fix.

**Comment by WORMSS** [comment]
@thedillonb  This bug seems to have regressed, as my co-worker is using 2.3.7 (2.3.7.1) and he edited a file on a development branch, and it made a commit and added the file on the master (default) branch. Such as @dannyti described. After that it either did a combination of match error and reports a sha id.

Or if we try to edit the file on the master branch (default) we get a communication interrupted error about 3 or 4 times after another. But then if we look on github, the change has been committed.

- Colin.

**Comment by dannyti** [comment]
Can confirm on the second issue posted above by worms.

**Comment by thedillonb** [comment]
Wow, I'm pretty embarrassed. I'm cooking a release to put out tonight which will contain the fix. Sorry about that. Not sure how that happened... #144 has been opened to track the regression.
