### ISSUE TITLE
All black when commenting

### ISSUE THREAD

**Issue by ooker777** [thedillonb/CodeHub#115]
![](http://i.imgur.com/X6ZKmrW.jpg)the preview mode is still OK

**Comment by sbrodehl** [comment]
Some issue here. 
In landscape mode this black thing appears and pushes the text up.
In portrait mode all is fine, the keyboard seems to position just over the black thing.

**Comment by Shawzborne** [comment]
Im sure he is aware of this issue, I have known about it since June when the iOS 8 beta 1 was released, I'm not exactly sure what the state of code hub is in right now

**Comment by sbrodehl** [comment]
That's right, using iOS 8.1.3
Looks like CodeHubs needs an update on iOS ... last version is from 09 Jul 2014, with a heads up for a huge 3.0 version?!
Seems more like CodeHub is dead.

**Comment by thedillonb** [comment]
@sbrodehl no not dead. Since this is just my leasure project I haven't had much time to dedicate to it. The next version is still on the way with plenty of fixes and lots of improvements; one of which is the fix for this issue.

![ios simulator screen shot feb 7 2015 3 19 58 pm](https://cloud.githubusercontent.com/assets/1644068/6093797/e5f91ae4-aedc-11e4-868d-d8fea37719d0.png)
