### ISSUE TITLE
Does it really needs to have write access?

### ISSUE THREAD

**Issue by umurgdk** [thedillonb/CodeHub#119]
Github oauth warns me about the app wants read/write permissions for public and even private repos. And this permission includes changing deploy keys and other critical stuff. I think there must be an option when we are logging in to choose less permissions.

**Comment by thedillonb** [comment]
Does the app have to have write access? No, if you don't want to use the creation functionaility for some of these things. GitHub will very soon implement functionaility to dynamically reduce permissions as the user sees fit. Once this is implemented you will be able to choose less permissions and the App will react accordingly by reducing the functionaility available to you. However, until then, I'm stuck asking for the whole lot because most users want the functionaility.

**Comment by thedillonb** [comment]
Closing this for now. I will re-open, or re-create, when GitHub enacts dynamic scope modifications so that users can choose their own permissions. Altering the scopes differently than what the app requests  will undoubtedly mean that functionaility of the app becomes disabled, which is a bummer, but gives the user piece of mind that they have now allowed write credentials to any app.

**Comment by willhains** [comment]
@thedillonb Sure, but full access to *personal user data* as well? Why does it need access to that?

**Comment by thedillonb** [comment]
@willhains, any application, without any scopes enabled, already has access to personal user data. If you are not interested in sharing that you may not want to use any third-party application. Like I said above, GitHub will soon be implementing more fine grained control over scopes which may allow you to restrict that kind of information from the app. But for now, there's no way to avoid displaying "personal information" to the app.

For example, just by authorizing the app, even if I disabled all the access scopes, I get the following data for my personal account:

```json

{
  "login": "thedillonb",
  "id": 1644068,
  "avatar_url": "https://avatars.githubusercontent.com/u/1644068?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/thedillonb",
  "html_url": "https://github.com/thedillonb",
  "followers_url": "https://api.github.com/users/thedillonb/followers",
  "following_url": "https://api.github.com/users/thedillonb/following{/other_user}",
  "gists_url": "https://api.github.com/users/thedillonb/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/thedillonb/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/thedillonb/subscriptions",
  "organizations_url": "https://api.github.com/users/thedillonb/orgs",
  "repos_url": "https://api.github.com/users/thedillonb/repos",
  "events_url": "https://api.github.com/users/thedillonb/events{/privacy}",
  "received_events_url": "https://api.github.com/users/thedillonb/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Dillon Buchanan",
  "company": null,
  "blog": "http://www.dillonbuchanan.com",
  "location": "Boston, MA",
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 38,
  "public_gists": 43,
  "followers": 231,
  "following": 4,
  "created_at": "2012-04-14T22:11:22Z",
  "updated_at": "2016-06-05T07:12:45Z"
}
```

**Comment by willhains** [comment]
@thedillonb OK then I guess the GitHub authorise screen is misleading? It said something to the effect of full access to all personal data, including private email addresses, etc.

Looking at my OAuth Applications settings now, I see CodeHub has access to "Update all user data".
Also, when I authorised another app earlier today, it didn't list "full access to personal data"... which seems to contradict what you're saying.

I don't doubt your intentions, but something seems amiss.

Here is the authorisation screen for "Branches":
![img_6180](https://cloud.githubusercontent.com/assets/1386812/15942208/7af7a81a-2ebe-11e6-9f8e-f88c4c1af0d5.jpg)

And here is the authorisation screen for CodeHub:
![img_6181](https://cloud.githubusercontent.com/assets/1386812/15942211/7b361f5a-2ebe-11e6-9926-aea71ae5cd19.jpg)
![img_6182](https://cloud.githubusercontent.com/assets/1386812/15942210/7b31d4ae-2ebe-11e6-9a5a-2a5f01a7ac30.jpg)

**Comment by thedillonb** [comment]
@willhains I believe the reason that Branches doesn't ask for the "user" permission (scope) is because it has no support for user profiles nor does it have any support for followers - both of which CodeHub does have support for.

For example, in CodeHub, you can actually see your followers and can add to whom your following. Without the "user" permission (access to personal data) then the application cannot view or add new followers.

I think this is an example of GitHub not having fine grained access permissions. For example, CodeHub doesn't care about private emails but the fact that it comes with the "user" scope means that it looks like CodeHub is going to modify it or read from it - which it doesn't. As GitHub continues to make finer grained access policies I will update the app in hopes that It makes it clearer to the user what the app is actually accessing.

**Comment by willhains** [comment]
@thedillonb I see. Thanks for the patient explanation!

One question: is the scope sent to GitHub at authorisation time? Or is it pre-registered with GitHub?

I'm wondering if CodeHub could ask the user what capabilities, and therefore what scope, they want to authorise, *before* the authorisation request is sent to GitHub. What do you think?

**Comment by thedillonb** [comment]
@willhains, scopes are sent at authorization so, yes, I could ask the user before hand if they accept these privileges. The only reason I don't is because GitHub announced, a while ago, that they would be presenting the user with the same screen upon authorization - so I was hoping to wait for them to do that before I put the work into it on my side. Unfortunately, I haven't heard any news about the feature being implemented in GitHub so hope is dwindling that they'll have it any time soon. I'll ping someone at GitHub and see if there is an ETA on it, if it's still a while out I'll implement it on my side.

**Comment by willhains** [comment]
Awesome. Thanks!
