### ISSUE TITLE
Notification misattributes PR closing

### ISSUE THREAD

**Issue by bretmartin** [thedillonb/CodeHub#133]
When I get a notification that a PR I submitted is closed, it says that I did it, even though it was done by someone else.

**Comment by bretmartin** [comment]
Example: https://github.com/wimnat/ansible-modules-extras/pull/1

Image of notification to follow

**Comment by bretmartin** [comment]
![](http://i.imgur.com/lzJla6i.jpg)

**Comment by caibo2014** [comment]
wow!

**Comment by caibo2014** [comment]
lgtm

**Comment by bretmartin** [comment]
@caibo2014 Not sure I follow -- do you mean "looks good" as in you don't see a bug here?

**Comment by dillonb123** [comment]
I started seeing this too. I'm investigating why this is happening

**Comment by thedillonb** [comment]
I just pushed out a re-worked notification service which addresses this issue. The problem was that it was taking the incorrect field in the notification. I've since modified it to take the "merged_by" field, or "closed_by" field to correctly reflect the user doing the action. You should start seeing these changes immediately in your notifications. If you see any other oddities we'll open this up again.
