### ISSUE TITLE
New user: unable to see any organizations

### ISSUE THREAD

**Issue by port8080** [thedillonb/CodeHub#134]
Hi Dillon
I installed CoderHub today and installed the 'GitHub Enterprise Support' upgrade.

I am not able to see the organizations I belong under "Profile->Organizations" - the iphone app is saying "No Organizations". I have attached a snapshot of what I expect to see using my browser.

Let me know if there is some setting that I need to change.

<img width="742" alt="screen shot 2015-08-24 at 12 34 08 pm" src="https://cloud.githubusercontent.com/assets/326830/9450298/b723a02e-4a5c-11e5-85a8-bc468a1fe27f.png">

**Comment by thedillonb** [comment]
Hello @port8080 , not too long ago GitHub made a change that may require you to give access to CodeHub via the Organization's Settings on GitHub. If you go to https://github.com (or your Enterprise instance), go to "Settings" and find your organization on the bottom left, click it, then go to "Third Party Access" and make sure there is no restrictions. If that doesn't work let me know and we can try a few other things.

**Comment by port8080** [comment]
Removed all the restrictions on  third party extensions; still not seeing my org in the app. Let me know if you need more info 

<img width="1060" alt="screen shot 2015-08-26 at 9 56 55 am" src="https://cloud.githubusercontent.com/assets/326830/9500186/dc2e88d4-4bd8-11e5-8917-77208dc3231e.png">

**Comment by thedillonb** [comment]
@port8080, hmm, very odd. I've only seen this happen one other time with another individual. I can't recall off the top of my head how we resolved it but I'll do some digging through my messages and see if I can figure out what's happening.

**Comment by mkoepke** [comment]
I just ran into this.

To fix:

1. Go to the github user account
2. Then Settings
3. Then Applications.
4. You should see CodeBox listed.   Click on it to drill down
5. At the bottom of the screen you should see Organizations listed for this user.
6. You need to specifically grant access to that organization

Now on the CodeBox app.  
1. Go to Settings and Delete Cache.  
2. Exit App and go to IOS Task Screen and kill the app.  
3. Restart CodeBox.   
4. Organizations should now be listed in the sidebar

**Comment by port8080** [comment]
:rocket:

**Comment by TiernanKennedy** [comment]
@thedillonb is there a way to make this work for Orgs that have to restrict third party Apps? We have it enabled and give access to only certain Apps.

**Comment by thedillonb** [comment]
@TiernanKennedy, unfortunately no. GitHub explicitly creates this limitation, on their side, to prevent unauthorized third-party apps from accessing an organization's resources. The app can't know that you belong to an organization, or access any of it's resources, unless GitHub provides that information in their API responses.

**Comment by TiernanKennedy** [comment]
@thedillonb ok fair enough thanks for the update

**Comment by supertedde** [comment]
I had the same problem. Understand that it would be possible to work around the problem by generally relaxing the access control in the organization settings. Due to the nature of our organizational setup and policies this is however not viable. This type of condition should be pointed out before one is lured to make a purchase. As it stands right now, I can not become a happy user who have paid for the upgrade, and I did not have a reasonable chance to foresee this. That responsibility rests upon you as a vendor. Do you have any suggestion to remedy the situation, or are you just happy to keep the money I paid with the given background?

**Comment by thedillonb** [comment]
@supertedde you had a comment on this thread but must have deleted it. However, I feel it's important to still answer you. If you are unable to use the app to visit an organization that has self imposed restrictions on it then you're welcome to ask for a refund from Apple. iOS developers have no control over providing refunds. However, I would point out that the app functions correctly as stated - it's a restriction that you, or your team, have put on the organization that is blocking access. Having to put a note that the app "will work with all organizations except the ones that you, or your team, restrict access" is a concern that is completely end-user imposed.

**Comment by supertedde** [comment]
I disagree. The note would need to say :
Does not work with organizations by default due to a default restriction in access settings. This can however be solved by changing access restrictions in the organization's settings.

**Comment by thedillonb** [comment]
But, @supertedde, there is already significant description of that in the app. The initial walkthrough, even before you sign up or are prompted with the "pro" version is the following:

![image1](https://cloud.githubusercontent.com/assets/1644068/22558181/ce9aa5ee-e93a-11e6-993a-50c5cbd8fe95.PNG)

The link provided, explains in full detail about organizational restrictions and how to approve them. It literally says, on the site, "When you create a new organization, third-party applications are restricted by default".

Not only that, when you login for the first time, and GitHub describes the access that you are giving to CodeHub they print the following:

![image1 1](https://cloud.githubusercontent.com/assets/1644068/22558276/1e251496-e93b-11e6-8935-88fd073b9015.PNG)

They are giving you the exact enumeration of organizations that CodeHub has access to.

**Comment by supertedde** [comment]
Ok. I trust you have done what's possible then. Usually I belong to the more diligent group of users, and therefore not used to fail due to unreasonable lack of attention from my side, but hey, I could be very wrong in this case. Learning that you insist this must what happened, so I rest my case. And it is very obvious from this conversation that failed use cases, such as mine, are far from ignored from your side. And that's a clear positive. Cheers

**Comment by jHackenthal** [comment]
As much as I hate to say it... other applications like "Working Copy" request approval appropriately to Organizational data that has restrictions on it and the responses that I have seen here are a pitiful lazy response due to proper developer education 404 not being found.

All in all great app but surely someone here should take some responsibility and implement what tons of other applications already do ... 3 ... years ... later. Then again if you do not know how to do it properly @Github would surely take your money just like you do for your users to aide in doing it correctly.

Sincerely a user that bought your high end application without the proper backend coding.

**Comment by garrettw** [comment]
@jHackenthal There's no need for the snide commentary at all. Dillon does the best he can with this app. Please see #436 where he was recently informed that it's now possible to do all that in the app. I can only assume it must not have been possible at some point in the past, and he was just never aware that it changed.
