### ISSUE TITLE
Locally storing of Repo on iDevices

### ISSUE THREAD

**Issue by dannyti** [thedillonb/CodeHub#145]
If possible , can we have codehub locally download/store the whole repo ?

The idea is that we should be able to edit files, folders when we are offline and once we go online, all those commits can be committed together to GitHub. 
Additionally, any commits to GitHub repo will be synced locally on iPhone. 

This will make codehub ahead of its time among all git related apps. 

Codehub can be a good rival to desktop GitHub clients.

**Comment by thedillonb** [comment]
Hey @dannyti, this is a great idea and one I plan on doing at one point. Downloading the source code for later viewing is the easy part. I'm not quite sure how i'll approach the edit and sync part. Because CodeHub does not have a native Git client built in that may be a troublesome area of development - especially if you think about having to add a whole Git client into the app it's size will be quite large.

**Comment by thedillonb** [comment]
@dannyti, I'm going to close this only because Git2Go has released an excellent product and is probably better than I can accomplish by merging GitHub & Git management into one app. I highly suggest checking it out if you haven't seen it already: http://git2go.com/
