### ISSUE TITLE
Payed push notifications breaks apple guidelines. 

### ISSUE THREAD

**Issue by BinaryBench** [thedillonb/CodeHub#181]
In the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/#push-notifications) apple specifies that: 

_"Apps cannot charge users for use of Push Notifications"_

Codehub only offers push notifications to premium users, which breaks said guidelines.

**Comment by thedillonb** [comment]
While you are correct, I don't particularly agree with this recent guideline addition. I actually pay for a VPS and the bandwidth it takes to poll GitHub and retrieve notifications so I can shovel them off to users. If I didn't have to pay for it, I wouldn't charge for it. However, because I do have to pay for those resources, I believe it's fair to ask for compensation. The notifications are not required for the app's operation (as many receive notifications via email) but they're a nice to have - along with the other Pro offerings.
