### ISSUE TITLE
accounts page shows account twice

### ISSUE THREAD

**Issue by FunTimeCoding** [thedillonb/CodeHub#20]
Im not sure if thats a bug or intended behavior. It leads me to assume that there might have been a glitch upon adding my account.

**Comment by thedillonb** [comment]
This will be fixed in the next version (3.0) as duplicate accounts, if they ever occur, are reconciled and collapsed into one. For example, attempting to add an account that already exists, CodeHub will recognize that the account has been added and just use that one:

![image](https://cloud.githubusercontent.com/assets/1644068/7217067/a2d59596-e5e4-11e4-89ee-0a65c7128e3f.png)
