### ISSUE TITLE
Authorization callback URL

### ISSUE THREAD

**Issue by andrewhart098** [thedillonb/CodeHub#200]
I apologize in advance if this question has been asked before or is very simple.  I'm new to Xamarin and I could not find an answer in the issues.  I did see #190, but that issue seems to have nothing to do with this app.  I'm specifically asking about CodeHub.

When trying to run the code locally I notice that GithubOAuthId and GithubOAuthSecret are not set in Secrets.cs.  When setting up an OAuth application via Github, you are promoted for an 'Authorization callback URL'.  What should this be in order to have the app run correctly locally?

**Comment by thedillonb** [comment]
Ah yes, the authorization callback is simply a domain which GitHub will kick the app browser back to so it can continue with the OAuth flow. This is currently hard coded into `LoginViewController.cs` in the "ShouldStartLoad". It's set to "dillonbuchanan.com". So, technically, you could set the Authorization callback URL to "dillonbuchanan.com" and it should work. Or, you can change that domain to "blabla.com" and it'll work too. It doesn't have to even be a valid URL since the app doesn't actually redirect to it. It just grabs the data from the URL.

Let me know if that helps. If not, open the issue again.

**Comment by jnawaz** [comment]
Dillon, I'm new to Xamarin and I'm trying to get the app running to have a look and see if I can resolve some issues that interest me. I can't seem to get past the stage where I select dotCom login, because the app crashes with the message "You must get your own key". As per your answer above, I have left the authorization callback URL to "dillbuchannon.com". 

Any suggestions to help me get past the login stage?

**Comment by thedillonb** [comment]
Hey @jnawaz, if you need to set a GitHub Application OAuth Secret and OAuth Id. The exception is originating from https://github.com/thedillonb/CodeHub/blob/master/CodeHub.Core/Secrets.cs which contains secrets that are not checked-in for obvious reasons. 

You can create your own `Id` and `Secret` by going to your Settings -> OAuth application -> Register New Application

**Comment by jnawaz** [comment]
Hey @thedillonb, thanks ever so much. I've got it up and running by generating the OAuth Secret and OAuth Id from within github. 

I'm hoping to make some solid contributions.

**Comment by rafaelbpa** [comment]
Just in case anyone is wondering where is it in 2018: Settings > Developers > OAuth apps (https://github.com/settings/developers).

**Comment by Headmast** [comment]
I create own OAuth Apps, set GithubOAuthId and GithubOAuthSecret. But after login in github via app, just opening Authorization callback URL page.

**Comment by cadkins052** [comment]
I agree

**Comment by Headmast** [comment]
@cadkins052, I resolved the question.  Default callback URL should be: "https://dillonbuchanan.com/"
https://github.com/CodeHubApp/CodeHub/blob/7c7df03cdee9f60de64a33b551d0fbc2ac9979d6/CodeHub.iOS/ViewControllers/Accounts/OAuthLoginViewController.cs#L60
