### ISSUE TITLE
No functionality whatsoever on 8.4

### ISSUE THREAD

**Issue by smileytechguy** [thedillonb/CodeHub#214]
I am running iOS 8.4, and cannot update due to jailbreak on a 32-bit device.  I am running the latest version that is compatible with 8.4, version 2.3.8.  Owned, starred, and trending show lists, but no repositories load.  I can't see any notifications either.

**Comment by thedillonb** [comment]
Are there any errors that pop up? Or is it just empty when you view the repositories or notifications? 

2.3.8 was a while ago so a drastic amount has changed since then. However, nothing in terms of the API has changed so the fact that some of it's not loading is very peculiar. I'm not sure what I'll be able to do, code wise, as to support iOS 8 again means that I'd have to cut functionality out of the current version.

**Comment by smileytechguy** [comment]
No errors, just nothing.  It may say "No repositories" or "No notifications", and the repository loads as a blank page
I have tried reinstalling

**Comment by thedillonb** [comment]
@smileytechguy I'm closing this as there's no possible way for me to correct this from a code perspective. The App Store gives me no tools to release a new version targeted at a lesser version without disrupting the current version for everyone else. I can't make the app iOS 8 supported again because it has features in there that are iOS 9 dependent so I'm stuck. 

I'm not sure why you're seeing issues around loading repositories in 2.3.8. That version isn't too old and didn't have such issues when it was originally released.
