### ISSUE TITLE
can you  help about git flow?

### ISSUE THREAD

**Issue by liujie15838028035** [thedillonb/CodeHub#273]
in the readMe.md ,i see
Contributions are absolutely welcome! The project is built on Xamarin, a free C# framework for iOS applications. You'll need to download this to build the project.

    Fork it!
    Create your feature branch: git checkout -b my-new-feature
    Commit your changes: git commit -am 'Add some feature'
    Push to the branch: git push origin my-new-feature
    Submit a pull request :D

i try it ,  i use git ,the commit log is:
![default](https://cloud.githubusercontent.com/assets/12193885/24833786/71ed530a-1d06-11e7-82aa-eccbb915843f.png)

the graph log is not a line, i want the graph log is a line , this is perfect, what should i do ? can you help me about what you do  when a pull request you recieve?

**Comment by liujie15838028035** [comment]
@thedillonb   can you help me ? the next graph log is verery perfect! can you help me about what you do when a pull request you recieve?
![default](https://cloud.githubusercontent.com/assets/12193885/24833824/280d0964-1d07-11e7-9350-d9fb0f6d4de0.png)

**Comment by thedillonb** [comment]
Its hard to get just a straight line. When you work locally, if you do a `git pull --rebase` instead of just a `get pull` it will help to keep your work on top of everyone elses. When you submit a pull request, the owner of the repository has an opportunity to rebase and merge the work, which also helps to keep the commit history in a straight line. CodeHub's linear commit history is mostly because I don't get a bunch of Pull Requests - so it's just me working on it and that leads to a straight line of history.

**Comment by thedillonb** [comment]
I'm closing this as there's no issue for CodeHub. However, feel free to continue the discussion.

**Comment by liujie15838028035** [comment]
okays thanks !  is it right ?  when i recieved a pull request ,  i do this 
git checkout  -b test

git remote add con1  https://github.com/con1/repo1.git
git remote add origin   https://github.com/origin/repo1.git
git pull --rebase con1 ISSUE1

git checkout master
git merge test
git push origin master

**Comment by liujie15838028035** [comment]
@thedillonb  is that right?
