### ISSUE TITLE
Organizations not showing up

### ISSUE THREAD

**Issue by jonathanmorgan** [thedillonb/CodeHub#300]
Two of my users are a member of a few github organizations.  I can't find the organizations in your application.  For the one, I do see at least one of the associated repositories.  For the other I do not.  Some of these are private repositories, but neither organization is entirely private.  I'd at least expect the organizations to show up in "Account --> organizations".  Might there be some settings on my accounts I need to change for this all to be visible to your application?  Thanks for any help.  - Jonathan

**Comment by jonathanmorgan** [comment]
I meant "profile --> organizations", not "accounts...".

**Comment by painterner** [comment]
I can't understand some of your words,I just want to share my codes in github.Orgnization is myself personal,isn't it? What should i do? I just add a orgnization name as painternerORG,can this help solve it?

发自我的 iPhone

> 在 2017年8月1日，19:55，Jonathan Morgan <notifications@github.com> 写道：
> 
> Might there be some settings on my accounts I need to change for this all to be visible to your application?

**Comment by kristenbca** [comment]
Shouldn't y'all just stop bullshiting the fuckin radio

**Comment by painterner** [comment]
How dare you say that, don't disturb me , your IQ is negetive?  Can you only curse others? Inner fragile gus!Roll home and don't go out again!!!


2017年8月1日 上午08:57，kristenbca <notifications@github.com> 写道：


Shouldn't y'all just stop bullshiting the fuckin radio

**Comment by wolfgangbaums** [comment]
Wtf!

> Am 02.08.2017 um 04:47 schrieb painterner <notifications@github.com>:
> 
> How dare you say that, don't disturb me , your IQ is negetive?  Can you only curse others? Inner fragile gus!Roll home and don't go out again!!!
> 
> 
> 2017年8月1日 上午08:57，kristenbca <notifications@github.com> 写道：
> 
> 
> Shouldn't y'all just stop bullshiting the fuckin radio

**Comment by thedillonb** [comment]
Hey @jonathanmorgan, the first thing to do would be to make sure those organizations have third-party access enabled for the app. You can find a walkthrough here: https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/.

**Comment by harishkavatekar** [comment]
I am not part of your organization. Remove me from your group.

**Comment by yogeshgo05** [comment]
I am not part of your organization and remove me as well .

**Comment by felixtejeda** [comment]
I am not part of your organization and remove me as well .

**Comment by snsparrow** [comment]
Please remove me as well.



On 4 Aug 2017, at 06:45, Felix Tejeda <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not part of your organization and remove me as well .

**Comment by radcomm** [comment]
Hi , i am not also not part of this organisation hence pls remove me .

**Comment by wolfgangbaums** [comment]
Me too please

**Comment by rangzf** [comment]
Im confused, remove me as well




发自网易邮箱大师
On 08/04/2017 14:08, wolfgangbaums wrote:
Me too please

**Comment by softwareboy92** [comment]
who are you? what is the matter?吕忠迪 (softwareboy)android开发工程师 - 亚信科技（中国）有限公司www.627291991@qq.com
            在2017年08月04日 17:45，让周飞 写道： Im confused, remove me as well




发自网易邮箱大师
On 08/04/2017 14:08, wolfgangbaums wrote:
Me too please

> Am 04.08.2017 um 07:45 schrieb Felix Tejeda <notifications@github.com>:
>
> I am not part of your organization and remove me as well .
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thedillonb/CodeHub","title":"thedillonb/CodeHub","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thedillonb/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rangzf in #300: Im confused, remove me as well\n\n\n\n\n发自网易邮箱大师\nOn 08/04/2017 14:08, wolfgangbaums wrote:\nMe too please\n\n\u003e Am 04.08.2017 um 07:45 schrieb Felix Tejeda \u003cnotifications@github.com\u003e:\n\u003e\n\u003e I am not part of your organization and remove me as well .\n\u003e\n\u003e —\n\u003e You are receiving this because you commented.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e\n\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread."}],"action":{"name":"View Issue","url":"https://github.com/thedillonb/CodeHub/issues/300#issuecomment-320206689"}}}

**Comment by snsparrow** [comment]
I just want to be unsubscribed from this mailing list.
On 4 Aug 2017, at 11:31, softwareboy <notifications@github.com<mailto:notifications@github.com>> wrote:



who are you? what is the matter?吕忠迪 (softwareboy)android开发工程师 - 亚信科技（中国）有限公司www.627291991@qq.com<mailto:www.627291991@qq.com>
在2017年08月04日 17:45，让周飞 写道： Im confused, remove me as well




发自网易邮箱大师
On 08/04/2017 14:08, wolfgangbaums wrote:
Me too please

> Am 04.08.2017 um 07:45 schrieb Felix Tejeda <notifications@github.com<mailto:notifications@github.com>>:
>
> I am not part of your organization and remove me as well .
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.








{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thedillonb/CodeHub","title":"thedillonb/CodeHub","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thedillonb/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rangzf in #300: Im confused, remove me as well\n\n\n\n\n发自网易邮箱大师\nOn 08/04/2017 14:08, wolfgangbaums wrote:\nMe too please\n\n\u003e Am 04.08.2017 um 07:45 schrieb Felix Tejeda \u003cnotifications@github.com<mailto:u003cnotifications@github.com>\u003e:\n\u003e\n\u003e I am not part of your organization and remove me as well .\n\u003e\n\u003e —\n\u003e You are receiving this because you commented.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e\n\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread."}],"action":{"name":"View Issue","url":"https://github.com/thedillonb/CodeHub/issues/300#issuecomment-320206689"}}}

**Comment by softwareboy92** [comment]
i can do what? i understand 吕忠迪 (softwareboy)android开发工程师 - 亚信科技（中国）有限公司www.627291991@qq.com
            On 08/04/2017 18:35, Sarah Sparrow wrote: I just want to be unsubscribed from this mailing list.

On 4 Aug 2017, at 11:31, softwareboy <notifications@github.com<mailto:notifications@github.com>> wrote:







who are you? what is the matter?吕忠迪 (softwareboy)android开发工程师 - 亚信科技（中国）有限公司www.627291991@qq.com<mailto:www.627291991@qq.com>

在2017年08月04日 17:45，让周飞 写道： Im confused, remove me as well









发自网易邮箱大师

On 08/04/2017 14:08, wolfgangbaums wrote:

Me too please



> Am 04.08.2017 um 07:45 schrieb Felix Tejeda <notifications@github.com<mailto:notifications@github.com>>:

>

> I am not part of your organization and remove me as well .

>

> —

> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub, or mute the thread.

>





—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

















{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thedillonb/CodeHub","title":"thedillonb/CodeHub","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thedillonb/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rangzf in #300: Im confused, remove me as well\n\n\n\n\n发自网易邮箱大师\nOn 08/04/2017 14:08, wolfgangbaums wrote:\nMe too please\n\n\u003e Am 04.08.2017 um 07:45 schrieb Felix Tejeda \u003cnotifications@github.com<mailto:u003cnotifications@github.com>\u003e:\n\u003e\n\u003e I am not part of your organization and remove me as well .\n\u003e\n\u003e —\n\u003e You are receiving this because you commented.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e\n\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread."}],"action":{"name":"View Issue","url":"https://github.com/thedillonb/CodeHub/issues/300#issuecomment-320206689"}}}

**Comment by snsparrow** [comment]
I somehow have been added to this mailing list and I wish to be removed from it.


On 4 Aug 2017, at 11:42, softwareboy <notifications@github.com<mailto:notifications@github.com>> wrote:



i can do what? i understand 吕忠迪 (softwareboy)android开发工程师 - 亚信科技（中国）有限公司www.627291991@qq.com<mailto:www.627291991@qq.com>
On 08/04/2017 18:35, Sarah Sparrow wrote: I just want to be unsubscribed from this mailing list.

On 4 Aug 2017, at 11:31, softwareboy <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:







who are you? what is the matter?吕忠迪 (softwareboy)android开发工程师 - 亚信科技（中国）有限公司www.627291991@qq.com<mailto:www.627291991@qq.com><mailto:www.627291991@qq.com>

在2017年08月04日 17:45，让周飞 写道： Im confused, remove me as well









发自网易邮箱大师

On 08/04/2017 14:08, wolfgangbaums wrote:

Me too please



> Am 04.08.2017 um 07:45 schrieb Felix Tejeda <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>>:

>

> I am not part of your organization and remove me as well .

>

> —

> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub, or mute the thread.

>





—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

















{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thedillonb/CodeHub","title":"thedillonb/CodeHub","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thedillonb/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rangzf in #300: Im confused, remove me as well\n\n\n\n\n发自网易邮箱大师\nOn 08/04/2017 14:08, wolfgangbaums wrote:\nMe too please\n\n\u003e Am 04.08.2017 um 07:45 schrieb Felix Tejeda \u003cnotifications@github.com<mailto:u003cnotifications@github.com><mailto:u003cnotifications@github.com>\u003e:\n\u003e\n\u003e I am not part of your organization and remove me as well .\n\u003e\n\u003e —\n\u003e You are receiving this because you commented.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e\n\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread."}],"action":{"name":"View Issue","url":"https://github.com/thedillonb/CodeHub/issues/300#issuecomment-320206689"}}}

**Comment by thedillonb** [comment]
Guys, if you don't want to be part of this repository's notifications then just unsubscribe! Responding to emails isn't going to help. At some point you "watched" this repository - simply "unwatch it". 

<img width="1043" alt="screen shot 2017-08-04 at 9 37 29 am" src="https://user-images.githubusercontent.com/1644068/28971097-cbafa93a-78f8-11e7-8a65-d3ac861f8eab.png">

Just hit the "Unwatch" button.

**Comment by Fonzie2014** [comment]
Me too remove me.

**Comment by Turpain2001** [comment]
Please remove me as well.

---------------------------------------------------------------



This e-mail, including any attachments, is intended solely for the person 
or entity to which it is addressed and may contain confidential, 
proprietary and/or non-public material. Except as stated above, any 
review, re-transmission, dissemination or other use of, or taking of any 
action in reliance upon this information by persons or entities other than 
an intended recipient is prohibited. If you receive this in error, please 
so notify the sender and delete the material from any media and destroy 
any printouts or copies.

**Comment by XiongJiangong** [comment]
don't send email to me any more




发自网易邮箱大师
On 08/04/2017 18:51, Sarah Sparrow wrote:
I somehow have been added to this mailing list and I wish to be removed from it.


On 4 Aug 2017, at 11:42, softwareboy <notifications@github.com<mailto:notifications@github.com>> wrote:



i can do what? i understand 吕忠迪 (softwareboy)android开发工程师 - 亚信科技（中国）有限公司www.627291991@qq.com<mailto:www.627291991@qq.com>
On 08/04/2017 18:35, Sarah Sparrow wrote: I just want to be unsubscribed from this mailing list.

On 4 Aug 2017, at 11:31, softwareboy <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:







who are you? what is the matter?吕忠迪 (softwareboy)android开发工程师 - 亚信科技（中国）有限公司www.627291991@qq.com<mailto:www.627291991@qq.com><mailto:www.627291991@qq.com>

在2017年08月04日 17:45，让周飞 写道： Im confused, remove me as well









发自网易邮箱大师

On 08/04/2017 14:08, wolfgangbaums wrote:

Me too please



> Am 04.08.2017 um 07:45 schrieb Felix Tejeda <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>>:

>

> I am not part of your organization and remove me as well .

>

> —

> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub, or mute the thread.

>





—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or mute the thread.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

















{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thedillonb/CodeHub","title":"thedillonb/CodeHub","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thedillonb/CodeHub"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rangzf in #300: Im confused, remove me as well\n\n\n\n\n发自网易邮箱大师\nOn 08/04/2017 14:08, wolfgangbaums wrote:\nMe too please\n\n\u003e Am 04.08.2017 um 07:45 schrieb Felix Tejeda \u003cnotifications@github.com<mailto:u003cnotifications@github.com><mailto:u003cnotifications@github.com>\u003e:\n\u003e\n\u003e I am not part of your organization and remove me as well .\n\u003e\n\u003e —\n\u003e You are receiving this because you commented.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e\n\n\n—\nYou are receiving this because you are subscribed to this thread.\nReply to this email directly, view it on GitHub, or mute the thread."}],"action":{"name":"View Issue","url":"https://github.com/thedillonb/CodeHub/issues/300#issuecomment-320206689"}}}

**Comment by rhettmartens** [comment]
Please take me off of this mailing list.

- Rhett

**Comment by stonedreamforest** [comment]
They're all idiots , You don't have to teach them how to use the github

**Comment by weguru** [comment]
Please take me off of this mailing list.

**Comment by garrettw** [comment]
Wow this is stupid. You all can remove yourselves from the email "list" by unwatching the repo.

**Comment by thedillonb** [comment]
I sincerely apologize to those who _actually_ want to be notified of updates to the project. The fact that some of the watchers don't seem to understand how GitHub works or, at the very least, understand how to read is absolutely mind boggling. 

Those of you who don't wish to receive updates anymore I strongly suggest you "Unwatch" the repository. If you continue to send messages to the issue board about "taking you off the mailing list" I will be submitting your name directly to GitHub's support team as harassment this project and those that also wish to be notified. I know that makes me sound like a dick, but, get it together guys - come on.

**Comment by rhettmartens** [comment]
Personal suggestion, your verbiage is not strong as you say reply to this
message or mute by following this link in the same sentence. Also note that
this is not how GitHub works, though this is a feature within GitHub that
the team at CodeHub has utilized, you may want to focus your effort on
providing an option for an "opt out" in email distribution because you are
likely going to be dealing with new people frustrated each day because they
don't know how they got into a massive email chain.

I definitely understand your own frustration though at getting barraged by
users who are stomping on your group, but you definitely want to try
finding a resolution for yourself and the people getting pulled into your
group through CodeHub, instead of getting pissed and "reporting" everyone.
Pretty sure GitHub won't look to kindly on that as they have no skin in the
game and are providing a service separate from yours. Best of luck! Hope
this helps a little.

V/R,

Rhett

**Comment by garrettw** [comment]
The emails are generated by Github automatically. Dillon, as the sole developer of CodeHub, has no control over the opt-out language included at the bottom of the emails.

**Comment by thedillonb** [comment]
@jonathanmorgan, sorry your original ask got lost in the nonsense about "unsubscribing". Please see if https://github.com/thedillonb/CodeHub#i-cant-find-my-organization solves your problem. Organization visibility, even if they are "public" is governed by access policies that is internal to GitHub. I believe by default, visibility to all third-party applications is actually denied. If you grant access then the app should be able to see them.

**Comment by jonathanmorgan** [comment]
It did.  All organizations visible now.  Thanks!

**Comment by NeehalTaneja** [comment]
Hey,
Sorry for an interruption, please remove me from the list of getting these messages, cause it’s been nearly a month and I am quite irritated with these notifications everyday.

Thanks,
Neehal Taneja

**Comment by harshilfx** [comment]
Me 2 

Thanks

**Comment by keithactive** [comment]
me too

> 在 2017年8月21日，12:06，harshilfx <notifications@github.com> 写道：
> 
> Me 2 
> 
> Thanks 
> 
> Sent from my iPhone
>

**Comment by garrettw** [comment]
All of you need to unsubscribe yourselves because there's no other way. You have to go to this CodeHub repo and Unwatch it.
