### ISSUE TITLE
App users auto-watched to this repo?

### ISSUE THREAD

**Issue by garrettw** [thedillonb/CodeHub#306]
The number of notifications I'm getting because of all the people who never wanted to watch this repo is a bit out of control. It's rather annoying and I wonder if there's any way you could get it calmed down (as I'm one who actually wanted to watch it).

Is it at all possible that you did something recently that caused the app to automatically watch this repo when people install it or log in?

Also, for the people who email back saying they want to be removed – would blocking and then unblocking them have the same effect as them clicking unwatch?

**Comment by wolfgangbaums** [comment]
I can only say that Unwatching and muting does not work. That's why forgive all the people who constantly say they want to be deleted from this thread. It's the same for me, it just does not work to unfollow. On top, we never subscribed, we just got this.

**Comment by bcordis** [comment]
Please contact github as the app has no email system built into it. It fallows the github notification settings.  https://help.github.com/articles/managing-notifications/

**Comment by thedillonb** [comment]
The app does not automatically sign you up to watch the repo - or even "start" it for that matter. The only place that could sign you up to watch the repo is located here: https://github.com/thedillonb/CodeHub/blob/c8b623e90006d7dabe015bd15260e6db27367d70/CodeHub.Core/ViewModels/App/StartupViewModel.cs#L114 which is **only** set if the user clicks "Watch" during the initial walkthrough (right after you download the app and run it for the first time). The only other way is to go to the repo, in the app, and click the action button and selecting "Watch". 

What I suspect people are doing is just randomly clicking "Watch" and "Star" on the walkthrough, completely oblivious to what those things mean in the context of GitHub - it is a GitHub app after all. The intention, obviously, is to allow people a way to get engaged with the project - not to spam them.

Unwatching an app has three choices: 

<img width="317" alt="screen shot 2017-08-07 at 3 17 54 pm" src="https://user-images.githubusercontent.com/1644068/29042111-a33cd5b2-7b83-11e7-85b3-85ecafef8cd3.png">

If people never want emails they would select "Ignore." If they select "Not Watching" they they will still get emails on threads they commented on because, as it clearly states, they will only get notified on threads they are participating or when mentioned. 

I, as the owner of the repo, have no control over removing people from the Watch list.

**Comment by thedillonb** [comment]
I have submitted a work item to GitHub support to remove **all** watch users. This is beyond bonkers and is probably just easier to ask them to reset the repository. If you really want to participate in getting notifications, please re-watch the repo - assuming they can actually wipe the list.

**Comment by thedillonb** [comment]
Closing this as there is no action I can take on my end except to continue explaining to people how to unsubscribe :/
