### ISSUE TITLE
No good read code experience as Octotree

### ISSUE THREAD

**Issue by codeguyFred** [thedillonb/CodeHub#317]

**Comment by jszaszvari** [comment]
Octotree is a chrome and Firefox plugin to view a tree of the code in a browser. Its not a git client...

**Comment by garrettw** [comment]
What does that have to do with CodeHub?

**Comment by thedillonb** [comment]
Perhaps the title is misleading? I'm gunna assume what he meant to say was that he'd like the code reading experience to be better on the app, similar to what Octotree provides. I can agree with that. Right now its really bare bone. Improving it is a good suggestion - although I'm not sure comparing it to Octotree will be a apples-to-apples comparison since, as @jszaszvari pointed out, it's a browser plugin and has way more landscape available.

I'm going to close this and open up a corresponding feature to improve code reading/navigation.
