### ISSUE TITLE
Last updated filter doesn't account for issues

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#38]
For example we constantly post issues in the tapatalk github

http://i.imgur.com/tlEB9Iu.jpg

**Comment by thedillonb** [comment]
The filtering here is governed by what comes back in GitHub's response for "LastUpdated" time. Unfortunately, if issue updates don't update that timestamp CodeHub does not know about it. Due to performance reasons, we cannot poll each repository for it's "true" updated timestamp as it would take way too long.

There is nothing CodeHub can do about this until it's addressed by GitHub.
