### ISSUE TITLE
Get rid of logging in and spinny at hard launch 

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#89]
Remove startup spinny and fade into Codehub

**Comment by thedillonb** [comment]
Not all users internet connections are a quick as others. The spinner helps to indicate that the app is communnicating with GitHub to load the profile of the user. Once loaded, it fades in. Otherwise, without some sort of loading indicator, you just stare at a static image thinking it froze.

![Load](http://g.recordit.co/Qc8kaUV7zi.gif)
