### ISSUE TITLE
Change Push Notification Wording and coding

### ISSUE THREAD

**Issue by Shawzborne** [thedillonb/CodeHub#90]
Instead of push notifications saying

"Zbaseballman2 opened issue thedillonb/CodeHub#12"

Say

"Zbaseballman2 created issue #12 in  the thedillonb/CodeHub repo"

And for opening/closing an issue say

"Zbaseballman2 closed issue #12 in  the thedillonb/CodeHub repo"

And if we want to customize it even more

Just say:

"Zbaseballman2 closed issue #12 in  the CodeHub repo"

**Comment by thedillonb** [comment]
Closing this as the notification user wording that ikkentim and johnthepink saw has been resolved via #133. As far as general wording of the notification goes, I'm going to leave it as it is for now. Two reasons: one is that it directly mimics the format that GitHub uses in the Event feed and the second being that because the notification has a size limit, I will tend to prefer smaller, more compact, wording to make sure the byte length is not reached - the 255 limit is not just the message but also the metadata for the app so it can correctly navigate to the view.
